#ifndef CUSTOMER_HPP
#define CUSTOMER_HPP

#include <cstdint>
#include <string>
#include <vector>

#include "./account.hpp"

class Customer{
      private:
            std::string Customer_name;
            std::uint64_t CustomerID;   // should be generated by bank // unsigned integer of 64-bits
            std::string government_ID;
            std::string phone_number;
            std::string eMail;
            std::string permanent_address;
            std::string customer_password;
            std::vector<std::string> accounts;   // one can have multiple accounts

      public:
            Customer(std::string &name, std::string &govt_ID, std::string &phNo, std::string &mail, std::string &addr, std::string &cus_pass);

            // getters
            std::string get_name() const;
            std::uint64_t get_customer_ID() const;
            std::string get_phone_no() const;
            std::string get_mail() const;
            std::string get_addr() const;
            std::vector<std::string> get_account_numbers() const;
            bool verify_customer_pass(const std::string& input_pass) const;

            // setters
            void set_phone_no(const std::string &ph_no);
            void set_addr(const std::string &address);
            void set_mail(const std::string &mail);
            void add_account(const Account &acc);
            bool remove_account(const std::string account_number);
};

void customer_login(void);
void customer_registration(void);
void delete_customer(void);

#endif